repos:
  - repo: https://github.com/ambv/black
    rev: 24.4.1
    hooks:
    - id: black
      language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8