[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
skip-string-normalization = true
exclude = "migrations"
[tool.isort]
profile = "black"
skip = "__init__.py"
multi_line_output = 3